### ISSUE TITLE
Epic: Database Identity Support

### ISSUE THREAD

**Issue by jvanasco** [sqlalchemy/sqlalchemy#5534]
Support for database "Identity" columns.

Components / Progress:
* [] Core/ORM Support - Creation
* [] Core/ORM Support - Reflection
* [] Specific Database Support

Tickets - SqlAlchemy:

* #5324 - PostgreSQL specific support for identity
* #5360 - Oracle specific support for identity
* #5362 - "generated as identity" core support
* #5527 - reflection of identity columns

Tickets - Alembic:

* https://github.com/sqlalchemy/alembic/issues/730 Alembic Support

**Comment by jvanasco** [comment]
closing in favor of Projects.
