### ISSUE TITLE
2.0 docs checklist

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#7863]
- [ ] update Query API docs so that every method refers to background on migrating to the 2.0 pattern, or the corresponding method on Select.  general format/ language to use is:

```
        .. seealso::

            This API is available using :term:`2.0 style` queries as well,
            documented at:

            * :ref:`queryguide_inspection`
```

- [ ] Declarative mappings need to use mapped_column()
- [ ] update tutorials to introduce mapped_column(), some tips/etc. regarding "what happened to Column()?" etc. describe they are equivalent
- [ ] new DeclarativeBase should be used everywhere instead of declarative_base() function
- [ ] update most Query usage to select()
- [ ] update central mypy docs in ORM guide
- [ ] more links in mypy extension to new mypy docs in ORM guide
- [ ] document annotation-enabled mapped_column() usage, likely in the ORM tutorial

**Comment by zzzeek** [comment]
dupe of #7659
